/**
 * Auto-Flag Matching Gifts
 *
 * Triggered when a new gift is created. Checks if the gift's matching_gift_status
 * is null or 'unknown', and if so:
 * 1. Creates an activity record to check employer match eligibility
 * 2. If the org has voice calls enabled, schedules an employer_match Flora call
 *    after a 3-day delay
 */

import { inngest } from '../client';
import { createAdminClient } from '@/lib/supabase/server';

export const autoFlagMatchingGifts = inngest.createFunction(
  {
    id: 'auto-flag-matching-gifts',
    name: 'Auto-Flag Matching Gifts',
    retries: 2,
  },
  { event: 'gift/created' },
  async ({ event, step }) => {
    const { giftId, contactId, organizationId, amount } = event.data;

    // Step 1: Fetch the gift and contact
    const giftData = await step.run('fetch-gift-and-contact', async () => {
      const supabase = createAdminClient();

      const { data: gift, error: giftError } = await supabase
        .from('gifts')
        .select('id, amount, matching_gift_status')
        .eq('id', giftId)
        .single();

      if (giftError || !gift) {
        throw new Error(`Failed to fetch gift: ${giftError?.message}`);
      }

      const { data: contact, error: contactError } = await supabase
        .from('contacts')
        .select('id, first_name, last_name, phone, phone_call_opt_out')
        .eq('id', contactId)
        .single();

      if (contactError || !contact) {
        throw new Error(`Failed to fetch contact: ${contactError?.message}`);
      }

      return { gift, contact };
    });

    // Step 2: Check if matching gift status needs flagging
    const status = giftData.gift.matching_gift_status;
    if (status !== null && status !== 'unknown') {
      return {
        skipped: true,
        reason: `Matching gift status already set: ${status}`,
      };
    }

    // Step 3: Create activity record
    const contactName = [giftData.contact.first_name, giftData.contact.last_name]
      .filter(Boolean)
      .join(' ') || 'Unknown Contact';
    const giftAmount = giftData.gift.amount ?? amount;

    await step.run('create-activity', async () => {
      const supabase = createAdminClient();

      await supabase.from('activities').insert({
        organization_id: organizationId,
        contact_id: contactId,
        activity_type: 'task_created',
        description: `Check employer match eligibility for ${contactName}'s $${Number(giftAmount).toLocaleString()} gift`,
        metadata: {
          giftId,
          autoGenerated: true,
          type: 'employer_match_check',
        },
      });
    });

    // Step 4: Check if org has voice calls enabled
    const orgSettings = await step.run('check-org-voice-settings', async () => {
      const supabase = createAdminClient();

      const { data: org } = await supabase
        .from('organizations')
        .select('voice_calls_enabled')
        .eq('id', organizationId)
        .single();

      return { voiceEnabled: org?.voice_calls_enabled ?? false };
    });

    // Step 5: If voice enabled and contact has phone, schedule an employer_match call
    if (
      orgSettings.voiceEnabled
      && giftData.contact.phone
      && !giftData.contact.phone_call_opt_out
    ) {
      // Wait 3 days before calling about employer match
      await step.sleep('wait-before-match-call', '3d');

      await step.run('schedule-employer-match-call', async () => {
        await inngest.send({
          name: 'voice/call.initiate',
          data: {
            contactId,
            organizationId,
            callType: 'employer_match',
            triggerEvent: 'gift/created',
            triggerEventId: giftId,
          },
        });
      });

      return {
        giftId,
        contactName,
        activityCreated: true,
        callScheduled: true,
      };
    }

    return {
      giftId,
      contactName,
      activityCreated: true,
      callScheduled: false,
      reason: orgSettings.voiceEnabled
        ? 'Contact has no phone or opted out'
        : 'Voice calls not enabled',
    };
  },
);
